export const coopPermissions = {
  selfRead: "coop.self.read",
  profileChangeRequest: "coop.profile.change.request",
  beneficiaryAssign: "coop.beneficiary.assign",
  sharesRead: "coop.shares.read",
  depositsRead: "coop.deposits.read",
  loansRead: "coop.loans.read",
  guaranteesRead: "coop.guarantees.read",
  dividendRead: "coop.dividend.read",
  statementRead: "coop.statement.read",
  documentsRead: "coop.documents.read",
  welfareRead: "coop.welfare.read",
  welfareRequest: "coop.welfare.request",
  serviceRequest: "coop.service.request",
  chatUse: "coop.chat.use",
  helpdeskCreate: "coop.helpdesk.create",
  membersRead: "coop.members.read",
  membersManage: "coop.members.manage",
  membersImport: "coop.members.import",
  membersExport: "coop.members.export",
  loansManage: "coop.loans.manage",
  dividendManage: "coop.dividend.manage",
  welfareManage: "coop.welfare.manage",
  documentsManage: "coop.documents.manage",
  requestsManage: "coop.requests.manage",
  chatManage: "coop.chat.manage",
  helpdeskManage: "coop.helpdesk.manage",
  announcementsManage: "coop.announcements.manage",
  reportsRead: "coop.reports.read",
  auditRead: "coop.audit.read"
} as const;

export type CoopPermission = (typeof coopPermissions)[keyof typeof coopPermissions];

export const coopPermissionCatalog: Array<{ key: CoopPermission; description: string; audience: "member" | "staff" }> = [
  { key: coopPermissions.selfRead, description: "อ่านข้อมูลตนเอง", audience: "member" },
  { key: coopPermissions.profileChangeRequest, description: "ขอแก้ไขข้อมูลสมาชิกและรูปโปรไฟล์", audience: "member" },
  { key: coopPermissions.beneficiaryAssign, description: "จัดทำคำขอมอบหมายสินทรัพย์ให้ทายาท", audience: "member" },
  { key: coopPermissions.sharesRead, description: "อ่านข้อมูลหุ้น", audience: "member" },
  { key: coopPermissions.depositsRead, description: "อ่านข้อมูลเงินฝาก", audience: "member" },
  { key: coopPermissions.loansRead, description: "อ่านข้อมูลเงินกู้", audience: "member" },
  { key: coopPermissions.guaranteesRead, description: "อ่านข้อมูลค้ำประกัน", audience: "member" },
  { key: coopPermissions.dividendRead, description: "อ่านข้อมูลปันผลและเฉลี่ยคืน", audience: "member" },
  { key: coopPermissions.statementRead, description: "ดาวน์โหลด Statement", audience: "member" },
  { key: coopPermissions.documentsRead, description: "อ่านเอกสารส่วนบุคคล", audience: "member" },
  { key: coopPermissions.welfareRead, description: "อ่านสิทธิ์สวัสดิการ", audience: "member" },
  { key: coopPermissions.welfareRequest, description: "ยื่นคำขอสวัสดิการ", audience: "member" },
  { key: coopPermissions.serviceRequest, description: "ยื่นคำร้องออนไลน์", audience: "member" },
  { key: coopPermissions.chatUse, description: "ใช้ Chat กับสหกรณ์", audience: "member" },
  { key: coopPermissions.helpdeskCreate, description: "เปิด Helpdesk Ticket", audience: "member" },
  { key: coopPermissions.membersRead, description: "ค้นหาและอ่านข้อมูลสมาชิก", audience: "staff" },
  { key: coopPermissions.membersManage, description: "จัดการข้อมูลสมาชิก", audience: "staff" },
  { key: coopPermissions.membersImport, description: "นำเข้าข้อมูลสมาชิก", audience: "staff" },
  { key: coopPermissions.membersExport, description: "ส่งออกข้อมูลสมาชิก", audience: "staff" },
  { key: coopPermissions.loansManage, description: "จัดการข้อมูลเงินกู้", audience: "staff" },
  { key: coopPermissions.dividendManage, description: "จัดการข้อมูลปันผล", audience: "staff" },
  { key: coopPermissions.welfareManage, description: "จัดการสวัสดิการ", audience: "staff" },
  { key: coopPermissions.documentsManage, description: "จัดการเอกสาร", audience: "staff" },
  { key: coopPermissions.requestsManage, description: "จัดการคำร้อง", audience: "staff" },
  { key: coopPermissions.chatManage, description: "จัดการ Chat", audience: "staff" },
  { key: coopPermissions.helpdeskManage, description: "จัดการ Helpdesk", audience: "staff" },
  { key: coopPermissions.announcementsManage, description: "จัดการข่าวสาร", audience: "staff" },
  { key: coopPermissions.reportsRead, description: "อ่านรายงาน", audience: "staff" },
  { key: coopPermissions.auditRead, description: "อ่าน Audit Timeline", audience: "staff" }
];
